from app.core.interfaces import (
    ICacheStrategy,
    IAIProvider,
    IRepository,
    IPageRepository,
    IPostRepository,
    IEmployeeRepository,
    IScraper,
    IPageService,
    AIAnalysisResult,
    PageResult,
    ScrapedPage,
)

from app.core.dependencies import (
    get_config,
    get_cache_strategy,
    get_cache_manager,
    get_ai_provider,
    is_ai_available,
    get_page_repository,
    get_post_repository,
    get_employee_repository,
    get_page_service,
    get_ai_analysis_context,
    AIAnalysisContext,
)

__all__ = [
    "ICacheStrategy",
    "IAIProvider",
    "IRepository",
    "IPageRepository",
    "IPostRepository",
    "IEmployeeRepository",
    "IScraper",
    "IPageService",
    "AIAnalysisResult",
    "PageResult",
    "ScrapedPage",
    "get_config",
    "get_cache_strategy",
    "get_cache_manager",
    "get_ai_provider",
    "is_ai_available",
    "get_page_repository",
    "get_post_repository",
    "get_employee_repository",
    "get_page_service",
    "get_ai_analysis_context",
    "AIAnalysisContext",
]
